[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "pome_treatment"
version = "0.0.1"
dependencies = []

requires-python = ">=3.8"

readme = "README.md"
